#!/bin/sh
#!/bin/sh -vx

set -eu

PATH='/bin:/local/bin'

led_='PWR'
if [ 'xACT' = x"$1" ] ; then
  led_='ACT'
fi
trig_path_="/sys/class/leds/${led_}/trigger"
bright_path_="/sys/class/leds/${led_}/brightness"

if [ 'xON' = x"$2" ] ; then
  echo 'none' | tee "$trig_path_"
  echo '1'    | tee "$bright_path_"

elif [ 'xOFF' = x"$2" ] ; then
  echo 'none' > "$trig_path_"
  echo 0      > "$bright_path_"

elif [ 'xTIMER' = x"$2" ] ; then
  echo 'timer' > "$trig_path_"

elif [ 'xHEARTBEAT' = x"$2" ] ; then
  echo 'heartbeat' > "$trig_path_"

fi
